### ISSUE TITLE
I2P and other Networks support and multi-profile 

### ISSUE THREAD

**Issue by katipiry** [maqp/tfc#121]
Hello!

Good morning, afternoon or evening! 

I would love to see support for other anonymity networks, such as I2P, Zeronet, Katzenpost, HyphaNet or Nym for example, as well as the possibility of having several temporary addresses on these networks (as in SimpleX. chat), this would be an extra layer in metadata protection, these two features would be incredible, and they could also have more protections such as signatures that guarantee that the device has not been tampered with in hardware, and another "upgrade" that I have already seen in a post drive on Reddit would be to upgrade to PQ ciphers (another thing that SimpleX.chat did, it would be nice to look at [their approach](https://simplex.chat/blog/20240314-simplex-chat-v5-6-quantum-resistance-signal-double-ratchet-algorithm.html#adding-quantum-resistance-to-signal-double-ratchet-algorithm)), thank you very much for your attention! 

Sincerely, Katipiry.

Note:
It would be a different address for each conversation (which is also temporary), plus you could create several accounts with different passwords (suppose a policeman points a gun at your head asking to have access to your messages, you could log in to another account so that he is tricked, and it would also be interesting to have a self-destruct button for all the data, for example enter an optional code for this), and another question I have, but are the messages self-destructive? 

That would be another great thing, and the queues like in SimpleX.chat that protect the user's IP even more, many of the SimpleX.chat protections if implemented in TFC would make it even more private and Anonymous.

**Comment by katipiry** [comment]
And other things I'd like to know, but the messages are filled with a fixed size? 
Is there break-in recovery? 
-
And it would be nice to have a look [here](https://simplex.chat/blog/20240314-simplex-chat-v5-6-quantum-resistance-signal-double-ratchet-algorithm.html#how-secure-is-end-to-end-encryption-in-different-messengers), at some protections that would make TFC even more secure and resistant to metadata.

**Comment by maqp** [comment]
I would love to see support for other anonymity networks, 

such as I2P, 

Zeronet, 
Katzenpost, HyphaNet or Nym for example, as well as the possibility of having several temporary addresses on these networks (as in SimpleX. chat), this would be an extra layer in metadata protection, these two features would be incredible, and they could also have more protections such as signatures that guarantee that the device has not been tampered with in hardware, and another "upgrade" that I have already seen in a post drive on Reddit would be to upgrade to PQ ciphers (another thing that SimpleX.chat did, it would be nice to look at [their approach](https://simplex.chat/blog/20240314-simplex-chat-v5-6-quantum-resistance-signal-double-ratchet-algorithm.html#adding-quantum-resistance-to-signal-double-ratchet-algorithm)), thank you very much for your attention!

**Comment by maqp** [comment]
>I2P

I2P is more or less a network where there's only the equivalent Onion Services but for stuff like torrents. TFC is already providing the security properties so it's not beneficial to split userbase into multiple protocols.

>Zeronet

Zeronet relies on Tor network for anonymity, so it's basically the same.

>Katzenpost

Has no Python library. Also, mixnets tend to be slower than Tor. They usually exist to provide high end-to-end correlation resistance for slow-paced communication like emails. TFC is about instant messaging.

>HyphaNet [aka freenet]

Has more emphasis on distributed data storage. It's not an anonymity network per se.

>Nym

See https://github.com/maqp/tfc/issues/30

---

I'd rather TFC uses the best tool for the purpose and for now, that's Tor. It attracts most funding, talent, scrutiny by security experts, and it's what the leaked slides show nation state adversaries consider the [toughest nut to crack](https://www.theguardian.com/world/interactive/2013/oct/04/tor-high-secure-internet-anonymity).

>for example, as well as the possibility of having several temporary addresses on these networks (as in SimpleX. chat), 

The UX is already stretching what people are comfortable with. Asking them to type both the TFC-account of each peer, and the public key, even just once, is a pain. It's only going to get worse once post-quantum key exchange mechanisms are implemented in the libraries TFC relies on. Asking the user to redo all that initial setup work after a contact jumps to another temp account, will wear the users out.

Also, I'm not entirely happy with how SimpleX handles things. You can see my criticism [here](https://discuss.privacyguides.net/t/simplex-vs-cwtch-who-is-right/19256).

>and they could also have more protections such as signatures that guarantee that the device has not been tampered with in hardware

I'm not sure what you're referring to here. Endpoint security in wider context for the endpoint is beyond the scope, but if there is a solid platform with solid verification mechanisms I might consider linking to that.

>upgrade to PQ ciphers

This is coming once the libraries support it. OpenSSL is making progress towards implementing Kyber in https://github.com/openssl/openssl/pull/25848 After that, it'll take a while before https://github.com/pyca/cryptography implements it. After that I can start looking into it.

>And other things I'd like to know, but the messages are filled with a fixed size?

Yes, TFC first compresses the message, then [adds PKCS7 padding](https://github.com/maqp/tfc/blob/master/src/common/crypto.py#L639), then splits the padded message into so called assembly packets that get encrypted with individual forward secret keys.

>Is there break-in recovery?

No: The double ratchet mechanism's future secrecy/break-in recovery is incompatible with TFC, as the user would have to type in the next advertised DH-ratchet key for every round trip, to Source Computer. Double ratchet exists to provide future secrecy, which **recovers** from remote key compromise. TFC exists to **prevent** remote key compromise, which I'd argue is better. Forward secrecy part is handled like in Signal protocol's non-round-trip mechanism, by using a hash ratchet.

---

So for the improvements, it's a 'no' for now, but if something like Nym becomes the dominating anonymity network with tangible improvements, I'm not opposed to switching to that. The PQ KEM will be adopted once it's available. Until then I'd advise using the pre-shared keys if you want post-quantum security.
