### ISSUE TITLE
USB-to-TTL adapter another place to buy instead of elektor store

### ISSUE THREAD

**Issue by johndoe-validator** [maqp/tfc#13]
Hello to all.
Did anyone find another place to buy FT232R USB-to-TTL adapter?
It is sold out in elektor store now =(
Google gives only FT232R**L**

@maqp maybe you know other place?
Thanks.

**Comment by maqp** [comment]
I'd imagine [this](https://www.elektor.com/ch340-usb-to-ttl-converter-uart-module-ch340g-3-3-v-5-5-v) gets the job done. You'll need some cables and possibly a box design of your own.

**Comment by maqp** [comment]
I'd imagine [this](https://www.elektor.com/ch340-usb-to-ttl-converter-uart-module-ch340g-3-3-v-5-5-v) gets the job done. You'll need some cables and possibly a box design of your own.

**Comment by maqp** [comment]
Looks like the model has been replaced with [a boxed one](https://www.elektor.com/ftdi-chip-ttl-232r-3v3-usb-to-uart-cable). The upside would be much less soldering. The downside is the output voltage is 3.3V, not 5V (also there's no longer a swtich), so the optocoupler's not going to work with it. The one linked above should work though.

**Comment by maqp** [comment]
To add, the [FOD8001](https://eu.mouser.com/Search/Refine?Keyword=FOD8001) optocoupler ([specs](https://eu.mouser.com/datasheet/2/308/FOD8001-1300831.pdf)) can run at 3.3V and has identical pin connectivity. But unfortunately it's not available in DIP-8 case but SOIC-8, so it would require a new PCB design that allows surface mounting the chip. Right now it seems better to use the replacement adapter instead.
