### ISSUE TITLE
what happened to the gpg key with this sha256 hash: 33ddcdda770e080f9a511884a3c18c138cc9b5fbb2dac1d64c6e3a36599bac69

### ISSUE THREAD

**Issue by eeparu** [maqp/tfc#15]
on the 24th of march this year, i went to github.com/maqp/tfc and saved the key needed to verify the integrity.
and now the only mention i can find of this key is in the comments of this blog post: https://www.schneier.com/blog/archives/2020/01/friday_squid_bl_714.html

has this repo been compromised?

**Comment by maqp** [comment]
Hi!

The key was updated prematurely as stated in the [update log](https://github.com/maqp/tfc/wiki/Update-Log#security-2) as I moved to new signing environment. The old key is still valid. Here's a detatched signature for the new [public key file](https://github.com/maqp/tfc/blob/master/pubkey.asc) signed with the old key:

```
-----BEGIN PGP SIGNATURE-----

iQIzBAABCAAdFiEEE3wqdU+qbbuozmTV+rAVyyKvL4QFAl42F9EACgkQ+rAVyyKv
L4SuHA//c5mpdLhQKJfGH0G+w78Zajnn8qFoHdr15yGCaGjyqHhAmJ9jBGlXcqLZ
NOODpKpRTk1R4j9R9LJIhvMY7zKwauJSISM24RGd00wXoXDnwNoLYlZeMLiDZTVc
llXQFPxKlhbFBrSTw2JDg3i2P5OzvvsgrfsgHv5H4hEs3JzFUkR51RQkrthMgvk5
i2covitC6D4+jlvKMPz5JqegbTUSyOadVqMe46Tv1PqM8F3fQxGuhAZ7jtzifrFm
fzltFhEGg54FyfjQLsU76EHAK7tIxo8YeARlDpcCOkxRHyrVIOrM7aiE0tWaLQch
rpoUNoX/keHc3d6L3Ege5olxwaLI/kSS3RZZtXDim7J07fGxW+EoKxZBuFVqHNZr
GvgGm/UFl8s+7Qtfjizltw3NhaDU/sHc73tpbub3Ssvk24qHZwYlB5EMQfOUgKv+
ytENc9qRNaIFSsDO1dQoQa48PWdyJNId0U/3+WAJzfQEVTnOKj8cGf9v8W/lhK7d
sFu8rk81j7seVQiAOx+OiAwsTVKeioxzF7607Kzm8/KhvrAHMFphKbMG218w8NoA
PNeumcx/Jp/V8OcA8jZytrizrJJ976uH2bEdefQxguwu5+hkZMKXbr5pgT2sui1W
4goqme+hVf/axavXkRNn/uDzMEnMk4N5sK45cxCqZAtrExKNFRI=
=DAHR
-----END PGP SIGNATURE-----
```

**Comment by eeparu** [comment]
Okay, thanks for clarification.
I was really confused because I couldn't find any mention of the old key in this repo anymore.

**Comment by eeparu** [comment]
i think the link to the old key should be https://github.com/maqp/tfc/blob/0202e4faa0e0e67c7e8d03d1ad947a6edbe4122c/pubkey.asc

**Comment by maqp** [comment]
Whoops, you're right, fixed!
