### ISSUE TITLE
Consider base 58-encoding public keys

### ISSUE THREAD

**Issue by elimisteve** [maqp/tfc#18]
miniLock does this and it results in very simple, unambiguous, and easy-to-type public keys that are only slightly longer!

But I should ask even before making the above suggestion: in what format are keys typed in now? as 32 integers (bytes)?

**Comment by maqp** [comment]
The public keys are already input in Base58, TFC uses Bitcoin's [WIF encoding](https://github.com/maqp/tfc/issues/18) so the values also have a checksum. Use of WIF was mentioned in [X448 protocol description](https://github.com/maqp/tfc/wiki/Security-design#x448) but I clarified that a bit more. Closing as a non-issue, feel free to comment or re-open if necessary.
