### ISSUE TITLE
invalid SHA512 hash for TFC-Local-test.desktop

### ISSUE THREAD

**Issue by BigNancyy** [maqp/tfc#29]
Trying to install the local testing version on Ubuntu 20.10. Installation fails at this: 

```
Error: /opt/tfc/launchers/TFC-Local-test.desktop had an invalid SHA512 hash:
5763c3f39f48a196767bc1c6b084d9b804f7df4f1c12f92bfd942897381142429419e29561e0e43039d865f5b44d0e64c91c55f0bf041f4a8ce5f4ed9e54c643
Expected following hash:
da4f1cc6f9f212f41f68610c196bdaf9a25572cc8f3952b69dc510635e059159f9e9625f6260abaaff2b5f5def01dd4f968e28bfe855a3133299b62030ce28e7
```

**Comment by BigNancyy** [comment]
Unsupported OS version, my apologies

**Comment by BigNancyy** [comment]
Reopening... issue persisted on Ubuntu 20.04 LTS

**Comment by maqp** [comment]
This was an actual bug that unfortuantely affected all installer configurations. I added automated checks to the release pipeline to detect such errors. Hopefully they will now be a thing of the past. Apologies for the inconvenience. I'm closing this as fixed, feel free to re-open and/or comment if necessary.
