### ISSUE TITLE
Invalid sha512 hash for Markupsafe 2.0.1---Networked Computer running Kubuntu

### ISSUE THREAD

**Issue by BigNancyy** [maqp/tfc#31]
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.                                   
    MarkupSafe==2.0.1 from https://files.pythonhosted.org/packages/7a/e8/00c435416c9b0238dca6f883563b01c4cc532b2ba6aaf7268081f6238520/MarkupSafe-2.0.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl#sha256=3dd007d54ee88b46be476e293f48c85048603f5f516008bee124ddd891398ed6 (from -r /opt/tfc/requirements-relay.txt (line 43)):                                                                     
        Expected sha512 10dbd4ab97a6ad405a938f0736f3ba5ec33c66b59b8420800e1df46c656e420566ba27e9917dfd11220e62028afad355fb21667f46a2c1cc765c987442a4b208                        
        Expected     or 1d046eae0c7a18fc9a09ff2ca52e8d05834eed7135dace51cc17286d4a98aebe32e806e9c581d445ce43eb7299856bdc3ca4870565ff2ba40dfbdae087904fd0                        
        Expected     or 41e98e2179f19955b0149a447154a1e9eec6358baa28476823547e0b4cecbc2621a266d93af009263511b86f56830c68ab063c20b6bf6edb7291fc938ea5b23f                        
        Expected     or 450469a14bb03cda262b70eaf6533cee5890695e30424e87866d829d4e97312a5766480fff7f55dae16733e56daa45cbeaf033e326a1580d18823108cba437d8                        
        Expected     or 46accdded7f03c49a6bb12d5e3765446ab59d5bf42fdd831e4cf04d591c434ae6642efe1208b06fb22192c979a5b5cbf8a242fb120d1402f048b6fe1f3e0627e                        
        Expected     or 7121a844bbd6738e28de4aca24cc2f49a810d468da519c5cf64e940afc80b6b01229125d6856b0b099a7f84f39da1327cab7a1cec5b1ab8a3aeaa4dcfe973646                        
        Expected     or 77249bda784111ece15d59eb3de1cbb37a58fb9f22902fe6b73fea9eb0f23857ccbe53dc55463278e3b91f78dc35e2b027fd823ca50d88d8985d5a98ce2327f1                        
        Expected     or 796b4d69860be9dc49a3642b477a1ba161a2ed21144a42d981aef0f8c9926d773cb7380af3b54088b84ec5b0007fda484a32c05b928788fc81b63039f95a8f2e                        
        Expected     or 7d72c81a908daae9f9c1a9ae220b6a24af7b8fb4cc7765f209c74616328236a7fc08e598aa1a68af6e8c563262f38eb6d869fcb445c4e39c4fb21bbfe49d140d                        
        Expected     or 8c02a6f72f55c8789c17b5795061b72b2964bfdc47a4956fcce9c5d7bef060ba682b9fce494256d135274407a37ab31e0048fe71ade5c0c4efefbfab18061b5c                        
        Expected     or 996409dc75f8b74fd6d061d597a00799c3157f4aa33d15e51dc7d7c5c527000d7dde79eace1924b5974c113ac90827ab354a2e58ec4707c62ed6a2136cc0c940
        Expected     or a946e2bd83c3babd5e5d5ff7d7320f023023cc5aac5928855f0fa8bc3bb56199c5b8dce09b06fde008432f753c6a7863779d6feb7c747e9efb8ee1938f3f8819
        Expected     or ad1ae4d16d8a8887b018e0f991ed0cc7414cafc92fd2d0dc8549dfd7e528e8be3d4085ce3419b06ccb06e96a4aebc1466522236dba480ac8d639b4bc7c8d6b25
        Expected     or b367223335bd0017bad2ffe6fab84214867d0b5b8aec7c849872bcf51f586c3fc3066d1f2155dc8ce75c6f8d7361a3daf6de086365ef54f609daa9f5cf50bc1f
        Expected     or b60deb0b4f5a34c70433f723a523434b56ccd76381abf71a2a57da86b8962b01ddc3d5ebeb090419f141a20583a43a23558c587ce97246687745b6c6ae47657d
        Expected     or d1a20c3fdc42f73476e2ac25c81d6220e915395651aa4e671539f349bca40135e4c9556a7ea04cae4cc426985035637a951a66a013897913984d44cf2628a789
        Expected     or e01a67f1d1dd3d55d5a377d062c9e95ba80030ce279777a074cbfe363258ad246ed1ecdea981a3d16420468d994e6ae9aae42276ff18558a14e146d28de5ae8c
        Expected     or e19b733bedd8ccc3e50ab54fea39d20ebb2af81a6137c0aed55315c1f7c8e13c3976ada5773e159935334f1aa6abcc4d7fff153d90d86de9e81d92bb90434f41
        Expected     or e393dc7df3f8c8afba005d8706d97bce2981ab43c83743b6f7d3c73e53f2844c9e1b67c929355cc06b938b8fb989efa92e3ace4e491a8c30857bc735893d7b4c
        Expected     or f28effef1954e22ad163b70ca6dde1d53010aacac4b33244372027383ded575fd68a193ebe0be76044f6dad4fea380b743dfd72bd87de1e8d84af2aa4291048e
        Expected     or f6a2d6e0ce38f8262aeed074c31cdabc46963b5e3970ed1a7af7f7557934fc08f15d53a017265a8c0a76b7be6133ffa257d3d92e6e4c2977cef329de94be5c57
             Got        c9e4d887b2a17572b895cdf12a618559311336edfc6175cece000d1e3aacf1a4a93c8a878dc945814a9ce534e6637d915e1f9f2d1ea6b78bd5e74f43c3f5fc47

**Comment by maqp** [comment]
Thanks for this! 

Hmm, looks like it's possible for even a same version of a dependency to receive new wheels, the hashes of which aren't naturally pinned. Shame, there's no way to fix this without removing hashes. I can (and will later) automate the process so I'll know when new wheels are added, but given the manual labor involved in signing, fixes won't be instant. The missing hash for the wheel is [included](https://github.com/maqp/tfc/blob/master/requirements-relay.txt#L78) in the latest release. Closing.
