### ISSUE TITLE
Data Diode Transfer Speeds

### ISSUE THREAD

**Issue by peterstory** [maqp/tfc#42]
I'm wondering what kind of transfer speeds the data diode designs support? This info could be a useful addition to the wiki!

**Comment by maqp** [comment]
The [HCPL-7723](https://eu.mouser.com/ProductDetail/Broadcom-Avago/HCPL-7723-000E?qs=s%252BgfxR24RQ7gIQcj6Xe%2F1Q==) optocoupler is rated for 50Mbps, and the current recommended [TTL-234X-5V](https://www.mouser.se/ProductDetail/FTDI/TTL-234X-5V/?qs=Mv7BduZupUgF3XwP6s6imA%3D%3D)  USB-to-TTL adapter is rated for 3Mbps.

The depicted TTL-adapter (by FTDI) worked well for 1Mbps but is no longer available. 

That being said, there's no definite answer as construction by hand, quality and physical distance of capacitors from the optocoupler, quality of the adapters all affect the error rate.

The default baudrate of 19200 is quite reliable assuming the HW components work and the assembly is correct. I think the user can attempt to increase that, and possibly experiment with the amount of error correction.

You're absolutely right this should be discussed in the documentation, I'll try to find some time at some point to expand on it. The project's mostly on hold for now as I try to focus on other aspects of my life.

**Comment by peterstory** [comment]
Thank you for sharing those details! I'm planning to build some data diodes this semester, so I'll let you know what TTL-adapters and other parts I use, and what transfer rates I can attain with them. Those transfer rates should be adequate for my project, though of course increasing them would be a nice bonus. :)

**Comment by maqp** [comment]
There is now a [FAQ entry](https://github.com/maqp/tfc/wiki/FAQ#which-baudrate-should-i-use) for selecting the baudrate. Closing.
