### ISSUE TITLE
Can we trust "Data Diode" ?

### ISSUE THREAD

**Issue by kokushkin** [maqp/tfc#9]
I see Data Diode is a key component in your system. As I understand you produce it. Also, kind of obvious, your system targets super secret messaging scenarios. Therefore, the level of trust in you should be higher than privacy level of information sending through your device. Have you considered a scenario where  end user solders "Data Diode" by yourself?

**Comment by DenisNovac** [comment]
I guess, you can't by the Data Diode from them, only make it by yourself:
https://github.com/maqp/tfc/wiki/TTL-Data-Diode-(breadboard)

**Comment by kokushkin** [comment]
O, it's cool, I see!

**Comment by maqp** [comment]
>Therefore, the level of trust in you should be higher than privacy level of information sending through your device

The FAQ discusses the [problems of selling pre-built systems](https://github.com/maqp/tfc/wiki/FAQ#why-not-offer-tfc-as-a-product-users-can-buy).

I'm doing my best to avoid anyone having to trust me at all. The data diode hardware circuits are open for anyone to see including the [FT232Rs](https://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT232R.pdf) and the [optocoupler](https://docs.broadcom.com/docs-and-downloads/optocouplers/AV02-0643EN_HCPL-7723_DS_2017-09-26.pdf) (I should probably add the links to the PDFs to the documentation).

Each data diode guide walks you through on how to build them, and discusses the issues of trusting the components, the interdiction problem, distributing trust when ordering the components, which SMT components are safe to order pre-assembled in the PCB version etc.

**Comment by maqp** [comment]
The ticket's been quiet for almost a fortnight now, I'm assuming @kokushkin you got the answer you wanted so I'm closing the ticket. Feel free to comment and re-open if needed.
